server:
  port: 8080
spring:
  application:
    name: spring-security
  redis:
    port: 6379
    host: localhost
  datasource:
    username: root
    password: newpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
  #thymeleaf
  thymeleaf:
    charset: UTF-8
    cache: false
    servlet:
      content-type: text/html
    #后缀
    suffix: .html
    #前缀 默认读取 classpath：/templates/
    prefix: classpath:/templates/